#+title: Bob Dylan 歌词收藏

** A Hard Rain’s A-Gonna Fall
#+BEGIN_VERSE
Oh, where have you been, my blue-eyed son?
Oh, where have you been, my darling young one?
I've stumbled on the side of twelve misty mountains
I've walked and I've crawled on six crooked highways
I've stepped in the middle of seven sad forests
I've been out in front of a dozen dead oceans
I've been ten thousand miles in the mouth of a graveyard
And it's a hard, and it's a hard, it's a hard, and it's a hard
And it's a hard rain's a-gonna fall

Oh, what did you see, my blue-eyed son?
Oh, what did you see, my darling young one?
I saw a newborn baby with wild wolves all around it
I saw a highway of diamonds with nobody on it
I saw a black branch with blood that kept drippin'
I saw a room full of men with their hammers a-bleedin'
I saw a white ladder all covered with water
I saw ten thousand talkers whose tongues were all broken
I saw guns and sharp swords in the hands of young children
And it's a hard, and it's a hard, it's a hard, it's a hard
And it's a hard rain's a-gonna fall

And what did you hear, my blue-eyed son?
And what did you hear, my darling young one?
I heard the sound of a thunder, it roared out a warnin'
Heard the roar of a wave that could drown the whole world
Heard one person starve, I heard many people laughin'
Heard the song of a poet who died in the gutter
Heard the sound of a clown who cried in the alley
And it's a hard, and it's a hard, it's a hard, it's a hard
And it's a hard rain's a-gonna fall

Oh, who did you meet, my blue-eyed son?
Who did you meet, my darling young one?
I met a young child beside a dead pony
I met a white man who walked a black dog
I met a young woman whose body was burning
I met a young girl, she gave me a rainbow
I met one man who was wounded in love
I met another man who was wounded with hatred
And it's a hard, it's a hard, it's a hard, it's a hard
It's a hard rain's a-gonna fall

Oh, what'll you do now, my blue-eyed son?
Oh, what'll you do now, my darling young one?
I'm a-goin' back out 'fore the rain starts a-fallin'
I'll walk to the depths of the deepest black forest
Where the people are many and their hands are all empty
Where the pellets of poison are flooding their waters
Where the home in the valley meets the damp dirty prison
Where the executioner's face is always well-hidden
Where hunger is ugly, where souls are forgotten
Where black is the color, where none is the number
And I'll tell it and think it and speak it and breathe it
And reflect it from the mountain so all souls can see it
Then I'll stand on the ocean until I start sinkin'
But I'll know my song well before I start singin'
And it's a hard, it's a hard, it's a hard, it's a hard
It's a hard rain's a-gonna fall
#+END_VERSE
** Mr Tambourine Man
#+BEGIN_VERSE
Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Though I know that evening's empire has returned into sand
Vanished from my hand
Left me blindly here to stand but still not sleeping
My weariness amazes me, I'm branded on my feet
I have no one to meet
And the ancient empty street's too dead for dreaming

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Take me on a trip upon your magic swirling ship
My senses have been stripped
My hands can't feel to grip
My toes too numb to step
Wait only for my boot heels to be wandering
I'm ready to go anywhere, I'm ready for to fade
Into my own parade
Cast your dancing spell my way, I promise to go under it

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

Though you might hear laughing, spinning, swinging madly across the sun
It's not aimed at anyone
It's just escaping on the run
And but for the sky there are no fences facing
And if you hear vague traces of skipping reels of rhyme
To your tambourine in time
It's just a ragged clown behind
I wouldn't pay it any mind
It's just a shadow you're seeing that he's chasing

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you

And take me disappearing through the smoke rings of my mind
Down the foggy ruins of time
Far past the frozen leaves
The haunted frightened trees
Out to the windy beach
Far from the twisted reach of crazy sorrow
Yes, to dance beneath the diamond sky
With one hand waving free
Silhouetted by the sea
Circled by the circus sands
With all memory and fate
Driven deep beneath the waves
Let me forget about today until tomorrow

Hey! Mr. Tambourine man, play a song for me
I'm not sleepy and there is no place I'm going to
Hey! Mr. Tambourine man, play a song for me
In the jingle jangle morning I'll come following you
#+END_VERSE
